### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by boskjoett** [rebus-org/Rebus.Async#19]
Any plans on promoting this package from "experimental" to "officially released"? It seems to work fine, and it very useful.

**Comment by mookid8000** [comment]
Well, I like to call it experimental because I don't really condone with the whole "synchronous request/reply over durable channels" thing 😅 

The thing is, when the requestor has transient state and cannot survive crash anyway, then it doesn't make sense to use durable  messages for request/reply – it would be better in every way to use some kind of RPC, like HTTP or Protobuf.

So... I think I'll go extend the text with some more words about why I think it's experimental.
