### ISSUE TITLE
How do I detect if RabbitMQ is unavailable?

### ISSUE THREAD

**Issue by boskjoett** [rebus-org/Rebus.Async#20]
When I call bus.Publish() and RabbitMQ has terminated I get a RabbitMQ.Client.Exceptions.BrokerUnreachableException or RabbitMQ.Client.Exceptions.AlreadyClosedException.

When I call bus.PublishRequest<TResponse>() in Rebus.Async I get a TimeoutException when RabbitMQ has terminated. I would prefer to have a RabbitMQ.Client.Exceptions.BrokerUnreachableException or RabbitMQ.Client.Exceptions.AlreadyClosedException in this case too.

Is there an easy way to be notified by Rebus when it has detected that the RabbitMQ connection has been lost?

**Comment by mookid8000** [comment]
Hmm I don't understand how it can give you a `TimeoutException`, because IIRC you will get that when waiting for the response.... but waiting for the response does not begin until after having sent the request, which should have resulted in `BrokerUnreachableException ` or `AlreadyClosedException`.

Could you post the full exception details here?

**Comment by boskjoett** [comment]
You are right, I get a BrokerUnreachableException or AlreadyClosedException exception. I will close the issue.
